// src/components/FatalError.svelte
<script lang="ts">
  import { globalState } from "../utils/state";
  import type Logger from "../utils/logger";
  export let logger: typeof Logger;

  const fatalMsgs = logger.log
    .slice()
    .filter(entry => entry.level === "fatal")
    .reverse();

  function handleReset() {
    logger.reset();
    globalState.gotoPage('INIT');
  }
</script>

<h2>Schwerwiegender Fehler aufgetreten</h2>
{#each fatalMsgs as entry}
  <p>{entry.message}</p>
{/each}
<div>
  <button type="button" on:click={handleReset}>Neustart</button>
</div>

// src/components/FatalError.tsx
import Logger from '../Logger';
import GlobalState from '../types/GlobalState';

function FatalError(props: { setGlobalState: React.Dispatch<React.SetStateAction<GlobalState>> }) {
    const handleReset = () => {
        Logger.reset();
        props.setGlobalState('GO_FOR_INIT');
    };

    return (
        <>
            <h2>Schwerwiegender Fehler aufgetreten</h2>
            {Logger.log
                .slice()
                .filter((entry) => entry.level === 'fatal')
                .reverse()
                .map((entry, i) => {
                    return <p key={i}>{entry.message}</p>;
                })}
            <div>
                <button type="button" onClick={handleReset}>
                    Neustart
                </button>
            </div>
        </>
    );
}

export default FatalError;
